### PR TITLE
update doctrine annotations to solve SdZv4 doctrine/* libs problems

### PR DESCRIPTION
**Pull request by alex-ception**
https://simple-it.atlassian.net/browse/OC-52739

### CODE REVIEW

**Comment by arnaud-23** [comment]
@alex-ception 
`Doctrine\Common\Cache\ArrayCache` seems to be in used but deprecated:

```PHP
 * @deprecated Deprecated without replacement in doctrine/cache 1.11. This class will be dropped in 2.0
 * @link   www.doctrine-project.org
 */
class ArrayCache extends CacheProvider
```

@sidux @Shivoham do you have idea for replacement ?

**Comment by alex-ception** [comment]
Some errors to fix in fact, project UseCase uses doctrine/annotations 2.x already :/

**Comment by alex-ception** [comment]
> @alex-ception `Doctrine\Common\Cache\ArrayCache` seems to be in used but deprecated:
> 
> ```
>  * @deprecated Deprecated without replacement in doctrine/cache 1.11. This class will be dropped in 2.0
>  * @link   www.doctrine-project.org
>  */
> class ArrayCache extends CacheProvider
> ```
> 
> @sidux @Shivoham do you have idea for replacement ?

Maybe PSR-6 or PSR-16 solution like symfony/cache (I don't know the impacts it would have)

**Comment by alex-ception** [comment]
In fact it is wrote in `OpenClassrooms\ServiceProxy\Handler\Impl\Cache\DoctrineCacheHandler` : `@deprecated use SymfonyCacheHandler instead`

**Review by Shivoham — APPROVED** [review]

**Comment by sidux** [comment]
I duplicated ArrayCache, as it's fastest solution for now

**Pull request closed without merging**
